# Build Stage
FROM node:18 AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

# Production Stage
FROM node:18-alpine
WORKDIR /app
COPY --from=build /app .
EXPOSE 5000
CMD ["node", "server.js"]
